sudo: false
language: node_js
node_js:
  - "12"
  - "10"
  - "8"

cache: npm

script: npm run test-ci

before_install:
- npm install -g coveralls

after_script:
- cat ./coverage/lcov.info | coveralls
